name: Build docker httpd and php-fpm containers

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Apache container and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/openconext/openconext-containers/openconext-httpd:latest
        context: docker/httpd/
        push: true
        secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Build the php-fpm prod container and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/openconext/openconext-containers/openconext-phpfpm:latest
        context: docker/php-fpm/
        target: fpmprod
        push: true
    
    - name: Build the php-fpm dev container and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/openconext/openconext-containers/openconext-phpfpm-dev:latest
        context: docker/php-fpm/
        target: fpmdev
        push: true
