name: Build docker container for the SP Dashboard

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build the Apache container and push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        dockerfile: docker/httpd/Dockerfile
        tags: openconext-containers/openconext-httpd:latest
        push: true
